#! /bin/bash
unset DISPLAY

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LAUNCH_DIR="$DIR/../launch"

timestamp_file=$LAUNCH_DIR/last_update

if [ ! -f "$LAUNCH_DIR/grid-client-core.jar" ]
then
    echo "First time run, downloading main application. This might take a little while..."
    java -Dsilent=true -jar "$LAUNCH_DIR/getdown-client.jar" "$LAUNCH_DIR"
else
    # checking whether last update was in the last 24 hours
    if [[ ( ! -f "$timestamp_file" ) || ( -n `find "$timestamp_file" -mmin +1440` ) ]]
    then
	echo "Checking for updates. This might take a while..."
	java -Dsilent=true -jar "$LAUNCH_DIR/getdown-client.jar" "$DIR"
    else 
	echo "Not checking for update, already checked today..."
    fi
fi

touch "$timestamp_file"

export X509_USER_PROXY="$HOME/.grid/grid.proxy"
#export JAVA_OPTS="-Djava.awt.headless=true -Xms128m -Xmx128m"

# check whether we have our own jvm
if [ -f "$LAUNCH_DIR/java_vm/bin/java" ]
then
	JAVA_EXE="$DIR/../launch/java_vm/bin/java"
else
	JAVA_EXE=`which java`
fi

"$JAVA_EXE" ${JAVA_OPTS} -cp "$DIR/../launch/grid-client-core.jar:$DIR/../launch/grid-client-dependencies.jar" grisu.frontend.gee.Gee "$@"
