#! /bin/bash

LAUNCH_DIR=`dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`
source "$LAUNCH_DIR/launch/prepare_cli.sh" "$@"

MAIN_CLASS="grisu.gricli.Gricli"

"$JAVA_EXE" ${JAVA_OPTS} -cp "$GRID_CLIENT_CLASSPATH"  "$MAIN_CLASS" "$@"
