#! /bin/bash

LAUNCH_DIR=`dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`
source "$LAUNCH_DIR/launch/prepare_gui.sh" "$@"

MAIN_CLASS="Grisu"

"$JAVA_EXE" ${JAVA_OPTS} -cp "$GRID_CLIENT_CLASSPATH"  "$MAIN_CLASS" "$@"

