#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export GETDOWN_DIR="$DIR/../launch"

export X509_USER_PROXY="$HOME/.grid/grid.proxy"
java -Dconnect_timeout=12 -jar "$DIR/../launch/getdown-client.jar" "$DIR/../launch" virtscreen
